config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/madgeek-arc/horizontal-adapters:
      branch: main
      repo: https://github.com/madgeek-arc/horizontal-adapters.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/madgeek-arc/horizontal-adapters git:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-brown-macaque.sh
        container: qc.acc_scaly-khaki-baboon
  QC.Doc:
    repos:
      github.com/madgeek-arc/horizontal-adapters find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-orchid-nightingale.sh
        container: qc.doc_leaky-pear-manatee
      github.com/madgeek-arc/horizontal-adapters git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-copper-saola.sh
        container: qc.doc_blurry-white-malamute
      github.com/madgeek-arc/horizontal-adapters markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-olivine-mau.sh
        container: qc.doc_sleazy-white-donkey
  QC.Lic:
    repos:
      github.com/madgeek-arc/horizontal-adapters licensee:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-black-chameleon.sh
        container: qc.lic_flaky-amethyst-fowl
  QC.Sec:
    repos:
      github.com/madgeek-arc/horizontal-adapters bandit:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-apricot-turtle.sh
        container: qc.sec_snippy-chartreuse-avocet
  QC.Sty:
    repos:
      github.com/madgeek-arc/horizontal-adapters checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-champagne-maltese.sh
        container: qc.sty_tasty-lime-beagle
      github.com/madgeek-arc/horizontal-adapters flake8:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-auburn-squid.sh
        container: qc.sty_gamy-red-ocelot
  QC.Uni:
    repos:
      github.com/madgeek-arc/horizontal-adapters pytest:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-sangria-fossa.sh
        container: qc.uni_sickly-pear-chameleon
  QC.Ver:
    repos:
      github.com/madgeek-arc/horizontal-adapters get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-denim-quail.sh
        container: qc.ver_snoopy-lilac-loon
timeout: 5400
