config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/madgeek-arc/horizontal-adapters:
      branch: main
      repo: https://github.com/madgeek-arc/horizontal-adapters.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/madgeek-arc/horizontal-adapters git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-peach-ragdoll.sh
        container: qc.acc_clammy-smalt-tetra
  QC.Doc:
    repos:
      github.com/madgeek-arc/horizontal-adapters find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-amethyst-rottweiler.sh
        container: qc.doc_nerdy-blue-beagle
      github.com/madgeek-arc/horizontal-adapters git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-magenta-robin.sh
        container: qc.doc_muzzy-purple-lionfish
      github.com/madgeek-arc/horizontal-adapters markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-heliotrope-dugong.sh
        container: qc.doc_snippy-ecru-hyena
  QC.Lic:
    repos:
      github.com/madgeek-arc/horizontal-adapters licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-orchid-tzu.sh
        container: qc.lic_jumpy-bistre-russel
  QC.Sec:
    repos:
      github.com/madgeek-arc/horizontal-adapters bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-cerise-avocet.sh
        container: qc.sec_woolly-rust-penguin
  QC.Sty:
    repos:
      github.com/madgeek-arc/horizontal-adapters checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.ready-asparagus-jaguar.sh
        container: qc.sty_goopy-yellow-birman
      github.com/madgeek-arc/horizontal-adapters flake8:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-cerulean-gopher.sh
        container: qc.sty_messy-indigo-alligator
  QC.Uni:
    repos:
      github.com/madgeek-arc/horizontal-adapters pytest:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-linen-dhole.sh
        container: qc.uni_paltry-buff-macaque
  QC.Ver:
    repos:
      github.com/madgeek-arc/horizontal-adapters get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-chocolate-uguisu.sh
        container: qc.ver_leaky-platinum-sheep
timeout: 5400
